name: "532_project"

channels:
  - conda-forge

dependencies:
  - python=3.11
  - altair
  - vl-convert-python
  - pandas
  - numpy
  - plotly
  - shiny
  - shinywidgets
  - watchdog
  - ibis-duckdb
  - sqlalchemy
  - anywidget
  - pip
  - pip:
    - kagglehub
    - chatlas
    - python-dotenv
    - shinychat
    - querychat
    - pytest
    - playwright
    - pytest-playwright
