# Variables
ENV_NAME = 532_project
PYTHON = python
SHELL := /bin/bash

# Colors for output
GREEN := \033[0;32m
YELLOW := \033[1;33m
RED := \033[0;31m
CYAN := \033[0;36m
RESET := \033[0m

.PHONY: help install db run clean

# Help command to list available commands
help:
	@echo -e "$(CYAN)Available commands:$(RESET)"
	@echo -e "  $(YELLOW)make install$(RESET)  - Create/Update the conda environment based on environment.yml"
	@echo -e "  $(YELLOW)make run$(RESET)      - Run the Shiny app in reload mode (development)"
	@echo -e "  $(YELLOW)make db$(RESET)       - Download and process the database"
	@echo -e "  $(YELLOW)make clean$(RESET)    - Remove all downloaded and processed data (requires confirmation)"

# Create or update the conda environment
install:
	@echo -e "$(GREEN)Creating/updating conda environment $(ENV_NAME)...$(RESET)"
	@if conda env list | grep -q "^$(ENV_NAME) "; then \
		conda env update -n $(ENV_NAME) --file environment.yml --prune; \
	else \
		conda env create -n $(ENV_NAME) -f environment.yml; \
	fi

db:
	@echo -e "$(CYAN)Downloading and updating database...$(RESET)"
	@$(PYTHON) src/data_loader.py
	@echo -e "$(CYAN)Processing data into parquet format...$(RESET)"
	@$(PYTHON) src/data_processor.py

# Run the Shiny app
# --reload requires 'watchdog' package and allows auto-restart on file save
run:
	@echo -e "$(GREEN)Running Shiny app in development mode...$(RESET)"
	@python -m shiny run src/app.py --reload --launch-browser

# Clean raw and processed data with confirmation
# Generated by Gemini 3.0
clean:
	@echo -e "$(RED)WARNING: This will remove all files in data/raw/ and data/processed/$(RESET)"
	@read -p "Are you sure you want to continue? [y/N] " -n 1 -r; \
	echo ""; \
	if [[ $$REPLY =~ ^[Yy]$$ ]]; then \
		echo -e "$(YELLOW)Cleaning data directories...$(RESET)"; \
		rm -rf data/raw/* data/processed/*; \
		echo -e "$(GREEN)Clean complete.$(RESET)"; \
	else \
		echo -e "$(CYAN)Clean aborted.$(RESET)"; \
	fi
